### ISSUE TITLE
CI failing on windows.

### ISSUE THREAD

**Issue by flaport** [flaport/klujax#5]
not sure whats going on yet...

@jan-david-fischbach

**Comment by jan-david-fischbach** [comment]
@flaport

We seem to get

error: 'CLOCK_MONOTONIC' undeclared

https://stackoverflow.com/questions/29666937/error-clock-monotonic-undeclared-first-use-in-this-function

I don't understand, why this shows up now...

**Comment by flaport** [comment]
seems to be an issue with SuiteSparse. Pinning SuiteSparse to the version we used last september fixes it for now.
