### ISSUE TITLE
support for python 3.13 ?

### ISSUE THREAD

**Issue by cpascual** [flaport/klujax#8]
I just found that klujax is not installable with the [recently released python 3.13](https://www.python.org/downloads/release/python-3130/).

Here is the output in my CI logs:
```
uv sync --dev --upgrade
Using CPython 3.13.0 interpreter at: /opt/hostedtoolcache/Python/3.13.0/x64/bin/python
Creating virtual environment at: .venv
Resolved 120 packages in 2.81s
error: Distribution `klujax==0.2.7 @ registry+[https://pypi.org/simple`](https://pypi.org/simple%60) can't be installed because it doesn't have a source distribution or wheel for the current platform
```

I am personally not in a hurry at all... just wanted to know if there are any blocking issues preventing the support of 3.13

**Comment by flaport** [comment]
Closing as as of version 0.2.9 wheels for python 3.13 are being built.
